### ISSUE TITLE
Default params in navigator route config

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/rfcs#36]
It may be useful to specify default params in some cases, eg: to reuse screens for multiple routes.

```js
let TabNavigator = createBottomTabNavigator({
  Brent: {
    screen: FriendScreen,
    initialParams: { firstName: 'Brent', lastName: 'Vatne' },
  },
  Eric: {
    screen: FriendScreen,
    initialParams: { firstName: 'Eric', lastName: 'Vicenti' },
  },
});
```

An alternative for this would be to wrap `FriendScreen` so we have `BrentFriendScreen` which passes in some props. This is maybe also fine and makes me hesitant to want to include something like `initialParams` unless we have some motivating use cases where this is infeasible. So let's gather use cases here.

**Comment by dantman** [comment]
> An alternative for this would be to wrap FriendScreen so we have BrentFriendScreen which passes in some props. This is maybe also fine and makes me hesitant to want to include something like initialParams unless we have some motivating use cases where this is infeasible. So let's gather use cases here.

I wouldn't say technically infeasible, but I don't think creating 6+ wrapper components for the same screen just because you can't pass in `initialParams` is a good model.

I used a hack to fake initialParams for this very use case in a released app. Though I got tired of DrawerNavigator's limitations and started a refactor to make a future version just use a single `Stack: StackNavigator()` route and handle drawer items and handle dispatching navigation myself with reset.

Every single drawer item visible in this screenshot is the same `Inbox` screen but with different params:
![screenshot_20180324-124905](https://user-images.githubusercontent.com/53399/37868348-e16e05bc-2f61-11e8-8b78-d08cb762a383.png)

**Comment by n1ru4l** [comment]
I will try to create a PR asap!

**Comment by ericvicenti** [comment]
Could we call this `defaultParams` instead? I think its more technically accurate, because the initial params of the route may be overridden by the navigation actions

**Comment by brentvatne** [comment]
here: https://github.com/react-navigation/react-navigation-core/pull/11

**Comment by donni106** [comment]
I also want to realize a Drawer with different items navigating in one same stack.
With setting up a `CustomDrawerItems` overwriting the `onItemPress` method, I am able to render the items and navigate correctly in one main stack. Using params didn't work for me.
![bildschirmfoto 2018-10-29 um 17 30 39](https://user-images.githubusercontent.com/1942953/47665144-bd2ea080-dba0-11e8-8603-a78217ff7bde.png)
My problem is, that the active item in my drawer is not changing. It is always the first item, which is active ('Start' in my example). I wonder how to set a clicked item active?

**Comment by brentvatne** [comment]
@donni106 - because it's not released yet, it's only in the latest alpha version of 3.0. post a new issue with exactly what you want
